### PR TITLE
Convert a lot of graphic packs to V4

### PR DESCRIPTION
**Pull request by Crementif**
Didn't update the docs (will do that tomorrow), but I manually checked (didn't verify them with the script but I did check if there wasn't anything too crazy that might screw things up and if there were any other signs that lead to issues) each pack to make sure that all the included ones are 99% safe.

I also didn't convert 5 graphic packs since they contained signs that needed to be manually checked or at least examined more:
- \Enhancements\TwilightPrincessHD_Bicubic (weird filter shenanigans)
- \Resolutions\DevilsThird_Resolution
- \Resolutions\TwilightPrincessHD_Resolution (this one just needs to be fully verified since it's popular enough and has like 27 shaders)
- \Resolutions\LegoStarWars_Resolution
- \Resolutions\TokyoMirage_Resolution (this one could also be verified with the script)

~~I hope I didn't make too many mistakes here.~~

### CODE REVIEW

**Comment by slashiee** [comment]
I trust that these changes are fine, especially after all the work you've done to the script after the first initial commit.

@getdls Are you able to verify that Twilight Princess HD shader edits work fine with Vulkan? You'll have to convert the pack itself.

Also: Tokyo Mirage Sessions #FE has a major graphical issue in Vulkan, but the shader edits should still be checked there as well. I'd prefer to get all the packs updated to v4 before we start working on v5.

**Comment by getdls** [comment]
@slashiee I can run a smoke test on a 2080 card, but that's kinda pointless considering that it's pretty much AMD and Intel users that run Vulkan.  

I figured that was that you guys/gals where doing with all that conversion and checking stuff.

**Comment by getdls** [comment]
**These work with Vulkan as is**

- LOD pack 
- Distant fog 
 

**Updated for Vulkan**

- Regular res pack - Shaders updated, UI scaling removed    
- Contrasty - Shader updated 
- FancyFX is broken - removed   .w /LOD shader based effects don't work in with Vulkan (Fire, heat haze, plant drool etc). 
- Bicubic crashes - removed .glsl doesn't work with Vulkan

**Comment by slashiee** [comment]
alright

**Comment by getdls** [comment]
jeebus f... merge errors.. abort abort!

**Comment by Crementif** [comment]
> **These work with Vulkan as is**
> 
> * LOD pack
> * Distant fog
> 
> **Updated for Vulkan**
> 
> * Regular res pack - Shaders updated, UI scaling removed
> * Contrasty - Shader updated
> * FancyFX is broken - removed   .w /LOD shader based effects don't work in with Vulkan (Fire, heat haze, plant drool etc).
> * Bicubic crashes - removed .glsl doesn't work with Vulkan

Which game are we talking about here?

**Comment by Crementif** [comment]
If we're talking about TPHD here, the scaling filters don't work with Cemu at the moment so I think we can just leave it.

**Comment by slashiee** [comment]
I think it's best to get rid of the TPHD Bicubic pack and wait for Cemu to add support for global packs so we can just use the Filter packs instead

**Comment by Crementif** [comment]
Yup, agree.

**Comment by getdls** [comment]
https://github.com/slashiee/cemu_graphic_packs/commit/55de532386ed7852fdbdd006c54e09dc2d62ef56 All done. 

If we get some multi selection option in v5 I'll move back multi-pass blur/FancyFX to the _resolution folder. Right now it doesn't know what the main settings are and will look like crap when it's wrong.

**Pull request merged**
