### PR TITLE
AMD light circles fix [Experimental]

### PR DESCRIPTION
**Pull request by valgusk**
- fixed dynamic light for me
- tower does not have circles anymore too, but I think it does not glow either

made by variable mashing at @alexkiri work

### CODE REVIEW

**Comment by alexkiri** [comment]
Hello! I'm glad to see you've found this useful.
I think you should remove all the hue/sat/value adjusting code (4 defines at the top, and some other 3+3 lines at the bottom. Compare it with the original shader, you'll see the difference.
Also, you should know that there are 4 shaders that render the reflection pass. Maybe you should add your fix to all of them?
shaders: (cf2e9b7aab93e342, e95d54571be1c0a9), 8e9e804a3cd384c3, 99122c964b6a1a19,

**Comment by kondorasGR** [comment]
im glad someone with AMD tries to fix this,any way i can test this?

**Comment by valgusk** [comment]
@kondorasGR, yes you can download my fork and it shouls have a new graphics pack named  "The Legend of Zelda: Breath of the Wild - AMD Light Circle fix"

**Comment by valgusk** [comment]
@alexkiri, thank you for providing ideas. Sadly I cannot test any change anymore, as I just sold my rx480.  I did not notice any of light glitches left, so other shader changes might even not be necessary

**Comment by kondorasGR** [comment]
well done!it fixed it for me too,especially in gerudo town!well done and thanks!

**Comment by Darth-Cthoras** [comment]
@valgusk I can test it on RX 480 - my CyberPowerPC is full AMD, so I'll give it a test run once merged.

**Comment by Xalphenos** [comment]
What's the hold up on merging?  Just tested this and it's working fine on an rx 460.  Even seems to be working correctly on 1.3.3.

**Comment by Darth-Cthoras** [comment]
Aye, confirmed on RX 480 - even Gerudo Village in 1.3.3 no longer has light circles, and that place was FULL of them due to having tons of light sources at night both 1.3.1 and 1.3.3.

**Pull request merged**
