### PR TITLE
[BotW] another shader to host contrasty

### PR DESCRIPTION
**Pull request by NAVras-Z**
Scrolling backwards through events until I found a shader that uses main texture, seems to have sth to do with bloom but I'm not sure. Needs proper testing.

### CODE REVIEW

**Comment by NAVras-Z** [comment]
oh yea it applies bloom in some way
org
with R1f commented
break180

**Comment by alexkiri** [comment]
This is good news. We can finally keep it clean. Are you sure the shader applies changes to everything?

**Comment by slashiee** [comment]
Why isn't the pack named Contrasty?

**Comment by NAVras-Z** [comment]
@alexkiri I think so...?
with R0f changed to 0,0,1:
blue
@slashiee ( ͡° ͜ʖ ͡°)

**Comment by NAVras-Z** [comment]
update: merge Adjustable Bloom into this Contrasty, since the original shader seems to be the final stage of bloom, also because before version2, Adjustable Bloom was part of Contrasty (in AA Removal)
original:
orgg
updated Contrasty with default value:
bloom

**Comment by Crementif** [comment]
Nice, now we can have everything graphically be enabled (?) within Cemu. I'd suggest having the packs have default values (so it looks like stock BotW) to prevent people having both Clarity in their resolution pack and Contrasty enabled at the same time having to screw with the settings to change it back.

**Comment by Crementif** [comment]
Got Jamie's confirmation that we're free to replace the old Contrasty with Clarity in the discord so we should probably change them all. Probably should leave this until we're sure everything is merged correctly and won't make an issue if someone would have clarity in their resolution pack.

**Comment by NAVras-Z** [comment]
I have some questions adapting clarity, so it's probably better Jamie him/herself make the change.

**Comment by NAVras-Z** [comment]
// no floor scale
// except saturation is used, but isn't signed a value, (0 by default?)
// fog color still black, doesn't remove anything
//defined gamma correction isn't used
//ContrastSaturationBrightness function isn't used ?looks like another crush color(tonemap)
//luminance coefficient rec.601(game) 0.2989,0.5866,0.1144 / srgb 0.2126,0.7152,0.0722
//gamma compressed before custom tone mapping
//double tone map 
//contrasty removed, only tone mapping left

**Comment by NAVras-Z** [comment]
regarding bd8bb, I got the formula, but no idea why it is like that.
looks like the color is already mapped at [0,1] and then clampped at //9
start from //10 seems to be post-processing,  saturation maybe? (the reason I reverted contrasty)
//10 and later removed
nosat
//original
org

**Comment by Crementif** [comment]
Sounds like you've got some really useful information here, good work.

>

**Comment by NAVras-Z** [comment]
Probably not gonna get anywhere but:
RGB is texture colors, Y luminance
linear color space

sorry for the clumsy writing

**Comment by NAVras-Z** [comment]
[bd8bba59e2149449_00000000000003c9_ps.txt](https://github.com/slashiee/cemu_graphic_packs/files/1406957/bd8bba59e2149449_00000000000003c9_ps.txt)
Requested by SkalFate on discord.
Keep in mind that I don't understand any of the formulas above so my assumptions are probably still wrong, or not good to modify it to begin with.

**Comment by NAVras-Z** [comment]
a quick guess i thought of
guess

**Comment by NAVras-Z** [comment]
eh... looks like A has sth to do with saturation (also the green tint because human eyes are more sensitive to green?)
uf_remapped.y changed from 0.18 to 1.0
green

**Comment by RaverX3X** [comment]
Nice.

**Comment by NAVras-Z** [comment]
oh looks like I was wrong about green tint, with it's own saturation adjust the color doesn't to green it seems
0.5:

original
orgno
could be that scene has too much green
anyway i tried to scale each color's increasement/decreasement, but ended up with more green... xD

**Comment by NAVras-Z** [comment]
[bd8bba59e2149449_00000000000003c9_ps.txt](https://github.com/slashiee/cemu_graphic_packs/files/1421384/bd8bba59e2149449_00000000000003c9_ps.txt)
mess with the original saturation, still based on those assumptions so i can't be sure.
default is 0.3

**Comment by NAVras-Z** [comment]
made a mistake at "A", forgot w at dot()

**Comment by NAVras-Z** [comment]
Color'' = mix(max, C', A)
A = remap.y * K + remap.x , [0.99, 1.17]
K = 1 - (1-2*avg)^2, K belongs to normal range [0,1]
avg = (R'+G'+B')/3, also [0,1]
Reminds me of how it controls the colors of loading screen, a multiplier and an addition, looks similar to this one's. 
Also i can't find a meaning without joining them together,
like A = 1 + 0.18(k - 0.01/0.18) looks more like a proper weight. (A>1 saturate)
(Perhaps uf_remap here are just calculated value without real meaning? @alexkiri )
So if want to control saturation just scale A with a factor, which is the same without changing where it saturates/unsaturates.

**Pull request closed without merging**
