### PR TITLE
Added Temporary Hyrule Warriors 30 FPS Lock.

### PR DESCRIPTION
**Pull request by MelonSpeedruns**
Hyrule Warriors runs the menus at 60fps. Because of that, they're twice as fast. Locking the FPS to 30 allows the menus to be at normal speed again. Also fixed the high-resolution pack. It was causing the background of the menus to be all black.

### CODE REVIEW

**Comment by slashiee** [comment]
Why remove everything but TV in rules.txt?

**Comment by MelonSpeedruns** [comment]
Like I said, it was causing the background menus to be black. I'll make an update with only that problem removed.

**Comment by slashiee** [comment]
Are all of those resolutions causing the issue?

**Comment by MelonSpeedruns** [comment]
See, that, I cannot confirm. I'll check which ones are causing issues today.

**Pull request merged**
