### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Darkemaste**
Add meta-less ID for Smash

### CODE REVIEW

**Comment by theboy181** [comment]
Sorry, what is meta-less do?

**Comment by slashiee** [comment]
makes the graphic pack work when theres no meta folder

**Comment by theboy181** [comment]
Would this be why updated mario kart 8 won't work?

**Comment by slashiee** [comment]
My MK8 is updated and it works perfectly fine, you probably updated the game incorrectly or something

**Comment by theboy181** [comment]
I'll retest.

**Pull request merged**
