### PR TITLE
Add modification packs for Xenoblade Chronicles X

### PR DESCRIPTION
**Pull request by lasyan3**
Add 2 new packs. One that increases collectibles range, other that allow customization of drop ratio for enemies loot.

### CODE REVIEW

**Comment by Crementif** [comment]
Don't have the game, but maybe someone else can review it?

**Comment by lasyan3** [comment]
Hi,

Just to explain a bit more what those 2 packs does (I'm planning to post the same text on cemu forum once the packs are online):
- **Collectibles range**: this pack strongly increases the distance from which you loot the collectibles. By default, you'll get them even before you're close enough to see the blue gem (distance increased by 52.0). There are 3 kind of distances in the game, each with a value of "Range" and "Height": "Inner" (which means when you are at foot), "Doll" (when you have a Skell at land) and "Flight" (which I believe is when you flight, generally in a Skell). Since I don't have a Skell yet in my current play, I would be grateful if someone could test the pack with its Skell (or even better, share with me its savegame). Right now I don't change the random selection of items (rare items are still rare).
- **Custom drop ratio**: this pack allows you to set a minimum drop ratio of **materials**. I insist on that: only materials seem concerned (if you get a gold chest, you'll still only get one or two weapon/armor, not all of them the enemy can drop). The default minimum ratio is 20%, but can easily be tweaked (if you set to always 100%, as long as the enemy drop a chest you'll get all materials from him). Second optional setting is to force the dropped chest (gold, silver or bronze). This setting was mainly for testing purpose, but some may find it interesting.

**Comment by slashiee** [comment]
What version of XCX does this use?

**Comment by Crementif** [comment]
After inspection, it seems that it only works without the updates. Did you use any updates?

**Comment by lasyan3** [comment]
I'm using 1.0.1E (module checksum is 0xF882D5CF). I think I have the DLC but gonna check.

**Comment by Crementif** [comment]
If I'm not wrong this won't work. The memory patch addresses are different for each module.

**Comment by lasyan3** [comment]
I've been able to get my hand on a 1.0.2U and this works for me as long as I add the module checksum 0x30B6E091 to the list of "moduleMatches". Still wait for someone else to confirm if possible.

**Comment by slashiee** [comment]
I need a save file where I can test these packs easily

**Comment by lasyan3** [comment]
Here: https://drive.google.com/file/d/0B5p7e1g-NHIvNU4tNjVvZ0RXbUU/view
(taken from https://www.youtube.com/watch?v=HdFC5jDox4o)

**Pull request merged**
