### PR TITLE
Add ClarityGFX pages via submodule, update some text.

### PR DESCRIPTION
**Pull request by Crementif**
The clarity pages work via submodules which will be updated at and mostly by [MelonSpeedruns repository](https://github.com/MelonSpeedruns/ClarityGFX_Presets) which will then listen to pull requests etc. The url will still belong to this repository, so https://slashiee.github.io/cemu_graphic_packs/clarity/. One minor point is that to retrieve his latest updates, you need to update the submodule via a console with the command `git submodule update --remote --merge` in the github branch. I'll try to take care of this whenever there's an update.

Due to the _data setup it's really easy to add Presets (https://github.com/MelonSpeedruns/ClarityGFX_Presets/blob/master/_data/presets.yml). The photo's can be clicked on to get a magnified look at it. Also, it doesn't have to be game exclusive, it's all placeholders for now. There's also support for multiple pictures in the form of the image slider, but currently we just have used 4 dublicate links.

The website can be previewed at https://crementif.github.io/cemu_graphic_packs/clarity/ .

### CODE REVIEW

**Comment by Crementif** [comment]
Also tagging @MelonSpeedruns .

**Comment by slashiee** [comment]
Probably once there's a few proper examples on the page present it can be merged

**Comment by slashiee** [comment]
any update?

**Comment by Crementif** [comment]
Mostly waiting for Clarity authors to settle down, but the presets keep being updated (which is a good thing) and the roadmap (I've talked with Serfrost and Jamie about this) isn't up to this point yet.

**Comment by Crementif** [comment]
Hm, think I'll close this down. Think the idea is not very wanted anymore and it's bothering me more to see an open pull request here 😄 .

**Pull request closed without merging**
