### PR TITLE
Created new BOTW Sharpening-only preset for Clarity

### PR DESCRIPTION
**Pull request by fabiograssiotto**
Hi,

For those people that want to keep BOTW original look, I created this pack that only applies sharpening.
It is good to offset the game AA. It is of course based off Clarity.
Do you think this could be added to as a new graphics pack?

Thanks,

### CODE REVIEW

**Comment by slashiee** [comment]
what's the difference between using this pack and just modifying clarity's settings to just use luma sharpening?

**Comment by fabiograssiotto** [comment]
It is exactly the same, only for people that do not want to or understand how to change #define statements. Perhaps it could be made into a profile for Clarity?

**Comment by mrtawsiti3** [comment]
i like this PR alot

**Comment by slashiee** [comment]
Yeah, a profile for Clarity makes more sense.

**Comment by fabiograssiotto** [comment]
Changed this into a Clarity Preset on the Clarity Presets folder.

**Pull request merged**
