### PR TITLE
[FatalFrameProjectZero]Resolution patch update

### PR DESCRIPTION
**Pull request by lilystudent2016**
Support for the widely used version in chinese-using areas, translated by chinese folk, based on JPN version.It will be quite convenient for chinese-using areas because most players choose this translated version to play. Can you add it to the patchs.txt?Thank you!

### CODE REVIEW

**Comment by lilystudent2016** [comment]
I`m so sorry that I wrote the wrong title.

**Comment by Crementif** [comment]
Do the graphic packs work with your chinese fan-translated version if you use your modifications?

If so, then I can add them.

**Comment by lilystudent2016** [comment]
> Do the graphic packs work with your chinese fan-translated version if you use your modifications?
> 
> If so, then I can add them.

Of,course.It`s tested by chinese cemu forum fans.I will show you the tested screenshots below.You know the ProjectZero doesn`t have offical chinese tanslation.Thank you so much!

**Comment by lilystudent2016** [comment]
before
Inked21a22e62f6246b60744b511cfcf81a4c500fa2baLI
after like this. FPS and resolution problems are fixed.
Inkedd53bb302738da9770e926543a751f8198718e342

**Comment by Crementif** [comment]
Merged both of the pull requests, thanks for your patience! Feel free to let me know if there are other changes that we could make to improve our graphic packs for chinese users. :smile:

**Pull request merged**
