### PR TITLE
Blur fixes for multiple games (MK8, Splatoon, SM3DW, CTTT)

### PR DESCRIPTION
**Pull request by Crementif**
**- Mario Kart 8 now has the general blur fix, added to Quality&Enthusiast.**
 + Fixed previous low radius
 + Added support for all resolutions by using general blur fix
 + Details: Used Horizontal&Vertical blur, 2 shaders added
Showcase

**- Splatoon now has the general blur fix, added to Quality&Enthusiast.**
 + Details: Used Horizontal&Vertical blur, 2 shaders added
Showcase

### CODE REVIEW

**Comment by slashiee** [comment]
Testing Splatoon, I have horizontal issues on 4k.
image

**Comment by Crementif** [comment]
Tested Mario Kart 8 on another computer and worked without any vertical shader issue. Potential issue with 1.10.0 maybe? It worked on both 1.9.2 and 1.8.0b for me. Need people to confirm the issue. Screenshot

**Comment by slashiee** [comment]
i think you need to update your fork with latest master. but you don't have to worry afterwards, as i'll give you push permissions to master once this PR is merged

**Comment by slashiee** [comment]
think you could fix the conflicts?

**Comment by Crementif** [comment]
Yes, I solved the conflicts and merged all commits done here.

**Comment by Crementif** [comment]
**- Fixed Captain Toad Treasure Tracker & Super Mario 3D World's weird light dots, added to Quality&Enthusiast.**
 + Details: Used Horizontal&Vertical blur, 2 shaders added.
Fixed
Without Fix

**Comment by Crementif** [comment]
Fixed conflicts again with your splatoon change.

**Pull request merged**
